"""add_user_certificates_table

Revision ID: 858658c3a6c4
Revises: 0009_aggregate_skills_data
Create Date: 2026-05-28 21:41:11.822871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
"""add_user_certificates_table

Revision ID: 858658c3a6c4
Revises: 0009_aggregate_skills_data
Create Date: 2026-05-28 21:41:11.822871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '858658c3a6c4'
down_revision: Union[str, Sequence[str], None] = '0009_aggregate_skills_data'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_certificates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('skill', sa.String(), nullable=False),
    sa.Column('cert_hash', sa.String(), nullable=True),
    sa.Column('tx_hash', sa.String(), nullable=True),
    sa.Column('contract_address', sa.String(), nullable=True),
    sa.Column('chain_id', sa.BigInteger(), nullable=True),
    sa.Column('network', sa.String(), nullable=True),
    sa.Column('verification_status', sa.String(), server_default='pending', nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('explorer_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cert_hash')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_certificates')
    # ### end Alembic commands ###
